package com.saez.susana;
import android.app.*;import android.content.*;import android.media.*;import android.net.Uri;import android.os.*;
public class AlarmService extends Service {
 public static final String CHANNEL="susana_reminders_v1"; private MediaPlayer player;private Vibrator vibrator;
 public int onStartCommand(Intent intent,int flags,int startId){String title=intent!=null?intent.getStringExtra("title"):"Recordatorio";String phase=intent!=null?intent.getStringExtra("phase"):"ahora";long id=intent!=null?intent.getLongExtra("id",System.currentTimeMillis()):System.currentTimeMillis();createChannel();Intent open=new Intent(this,AlarmActivity.class);open.putExtra("title",title);open.putExtra("phase",phase);PendingIntent pi=PendingIntent.getActivity(this,(int)(id%Integer.MAX_VALUE),open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification n=new Notification.Builder(this,CHANNEL).setSmallIcon(R.drawable.ic_susana).setContentTitle("💜 Susana te recuerda").setContentText(phase.equals("ahora")?title:title+" · "+phase).setCategory(Notification.CATEGORY_ALARM).setPriority(Notification.PRIORITY_MAX).setVisibility(Notification.VISIBILITY_PUBLIC).setOngoing(true).setFullScreenIntent(pi,true).setContentIntent(pi).build();startForeground(7701,n);ring();return START_NOT_STICKY;}
 private void createChannel(){if(Build.VERSION.SDK_INT<26)return;NotificationManager nm=getSystemService(NotificationManager.class);if(nm==null)return;Uri sound=RingtoneManager.getDefaultUri(RingtoneManager.TYPE_ALARM);AudioAttributes at=new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ALARM).build();NotificationChannel ch=new NotificationChannel(CHANNEL,"Recordatorios de Susana",NotificationManager.IMPORTANCE_HIGH);ch.enableVibration(true);ch.setSound(sound,at);ch.setDescription("Avisos importantes y recordatorios personales");nm.createNotificationChannel(ch);}
 private void ring(){try{Uri u=RingtoneManager.getDefaultUri(RingtoneManager.TYPE_ALARM);player=new MediaPlayer();player.setDataSource(this,u);player.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ALARM).build());player.setLooping(true);player.prepare();player.start();}catch(Exception ignored){}try{if(Build.VERSION.SDK_INT>=31){VibratorManager vm=getSystemService(VibratorManager.class);if(vm!=null)vibrator=vm.getDefaultVibrator();}else vibrator=(Vibrator)getSystemService(VIBRATOR_SERVICE);if(vibrator!=null)vibrator.vibrate(VibrationEffect.createWaveform(new long[]{0,800,250,800,250,1200},0));}catch(Exception ignored){}}
 public void onDestroy(){if(player!=null){try{player.stop();}catch(Exception ignored){}try{player.release();}catch(Exception ignored){}}if(vibrator!=null)try{vibrator.cancel();}catch(Exception ignored){}stopForeground(STOP_FOREGROUND_REMOVE);super.onDestroy();} public IBinder onBind(Intent i){return null;}
}
